name: hello-world-vettrivel
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Setting up job"
      
      - name: Print Your Name
        run: echo "Hello World - Vettrivel"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t vettri12/ml-model-22IT053 .

      - name: List Docker Images
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push vettri12/ml-model-22IT053

      - name: Post Login to Docker Hub
        run: echo "Logged out of Docker Hub"

      - name: Post Checkout Repository
        run: echo "Checked out repository"

      - name: Complete job
        run: echo "Job completed successfully"
