name: hello-world-vettrivel
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Your Name
        run: echo "Hello World - Vettrivel"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t vettri12/ml-model-22IT053 .

      - name: Docker Images
        run: docker images
