name: hello-world-vettrivel
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Your Name
        run: echo "Hello World - Vettrivel"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: sudo apt-get update && sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: docker build -t vettri12/ml-model-22IT053 .

      - name: List Docker Images
        run: docker images
